### ISSUE TITLE
Remove object spy/heal icon from IDE

### ISSUE THREAD

**Issue by JPBorude08** [ing-bank/INGenious#13]

**Comment by ghoshasish99** [comment]
Removed the following icons from tool bar :


1‍⃣  Object Spy & Heal - These features are present in Playwright Inspector window itself, which opens up when we use the following 2 options :

   - Recording at the very start ⏺️
   - Record from here (in the middle of test execution)

2‍⃣  Image Object Recording - This feature is deprecated
