### ISSUE TITLE
Remove functionalities from Run settings which are still "under test"

### ISSUE THREAD

**Issue by JPBorude08** [ing-bank/INGenious#15]

**Comment by ghoshasish99** [comment]
Removed the following options : 

1‍⃣  Auto Heal - This will be added in future releases after enhancements
2‍⃣  Excel Reporting  - Obsolete
3‍⃣  Send Mail After Execution - This feature is removed from INGenious and the advise is to leverage the email capabilities of the CICD tool

**Additionally** - The Bevel border has been changed to Empty Border for the JPanels
